name: json_model
description: Gernerating Dart model class from Json file.
version: 0.0.4
author: wendux <824783146@qq.com>
homepage: https://github.com/flutterchina/json_model

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  args: ^1.5.2
  build: ">=1.2.0 <1.3.0"
  glob: ^1.1.7
  logging: ^0.11.3+2
  io: ^0.3.0
  build_resolvers: ^1.1.1
  build_runner_core: ^4.1.0
  build_runner: ^1.7.1
  json_annotation: ^3.0.0
  json_serializable: ^3.2.3
  path: ^1.6.4
dev_dependencies:
  test: ^1.9.1
